Imported Modules

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import plotly.graph_objects as go
import plotly.figure_factory as ff


Getting Data for Handwritten Digits from MNIST

In [2]:
(X_train, y_train), (X_test, y_test) = keras.datasets.mnist.load_data()

In [3]:
print(f"Size of training set: {len(X_train)}")
print(f"Shape of traning set: {X_train.shape}")
print(f"Size of test set: {len(X_test)}")
print(f"Shape of test set: {X_test.shape}")

Size of training set: 60000
Shape of traning set: (60000, 28, 28)
Size of test set: 10000
Shape of test set: (10000, 28, 28)


In [4]:
go.Figure(data=go.Heatmap(z=X_train[1], colorscale='gray')).show()

In [5]:
X_train[1]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  51, 159, 253, 159,  50,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  48, 238, 252, 252, 252, 237,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

Flattern the Image Input for Neural Network Inputs

In [6]:
flat_X_train = X_train.reshape(len(X_train), 28*28)
flat_X_test = X_test.reshape(len(X_test), 28*28)
print(f"Shape of flat training set: {flat_X_train.shape}")
print(f"Shape of flat test set: {flat_X_test.shape}")

Shape of flat training set: (60000, 784)
Shape of flat test set: (10000, 784)


In [7]:
X_train[0]
#As we can see each image is now represented as a 1D array of 784 values.

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

Sclaing the Input Data

In [8]:
scaler = MinMaxScaler()
scaled_X_train = scaler.fit_transform(flat_X_train)
scaled_X_test = scaler.transform(flat_X_test)

Creating the Neural Network Model to Classify Handwritten Digits

In [26]:
keras.backend.clear_session()
model = keras.models.Sequential([
    keras.layers.Dense(100, input_shape=(784,), activation='relu'),
    keras.layers.Dense(10, activation='sigmoid')
])

# Points to Noted
# 1. Here Sequential means that we have a stack of layers in our model.
# 2. Dense means that neurons present in the model are fully connected.
# 3. Input shape is 784 because each image is represented as a 1D array of 784 values.
# 4. Activation function is relu for the first layer and sigmoid for the second layer.
# 5. The hidden layer has 100 neurons and the second layer or output layer has 10 neurons.

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Points to Noted
# 1. Optimizer is used to update the weights of the neurons. To find minima of the loss function.
# 2. Loss function is used to measure how well the model did on training.
# 3. Metrics is used to monitor the training and testing steps. Here we are using accuracy, the fraction of the images that are correctly classified.

# sparse_categorical_crossentropy is used in case of multi-class classification problem.

model.fit(scaled_X_train, y_train, epochs=10, batch_size=32, validation_split=0.1)

# Points to Noted
# 1. Epochs is the number of times the model will cycle through the data.
# 2. Batch size is the number of images that will be passed through the model at one time.
# 3. Validation split is the fraction of the training data that will be used for validation.

Epoch 1/10
1688/1688 [==============================] - 6s 3ms/step - loss: 0.2854 - accuracy: 0.9197 - val_loss: 0.1355 - val_accuracy: 0.9625
Epoch 2/10
1688/1688 [==============================] - 5s 3ms/step - loss: 0.1271 - accuracy: 0.9632 - val_loss: 0.0928 - val_accuracy: 0.9743
Epoch 3/10
1688/1688 [==============================] - 6s 3ms/step - loss: 0.0885 - accuracy: 0.9746 - val_loss: 0.0864 - val_accuracy: 0.9747
Epoch 4/10
1688/1688 [==============================] - 5s 3ms/step - loss: 0.0666 - accuracy: 0.9804 - val_loss: 0.0845 - val_accuracy: 0.9743
Epoch 5/10
1688/1688 [==============================] - 5s 3ms/step - loss: 0.0529 - accuracy: 0.9841 - val_loss: 0.0716 - val_accuracy: 0.9778
Epoch 6/10
1688/1688 [==============================] - 5s 3ms/step - loss: 0.0410 - accuracy: 0.9881 - val_loss: 0.0879 - val_accuracy: 0.9745
Epoch 7/10
1688/1688 [==============================] - 5s 3ms/step - loss: 0.0359 - accuracy: 0.9888 - val_loss: 0.0943 - val_accuracy:

Evaluating the Neural Network Model Accuracy

In [27]:
model.evaluate(scaled_X_test, y_test)
# we can see that the accuracy of the model is 92.5% on the test set.

313/313 [==============================] - 1s 2ms/step - loss: 0.0868 - accuracy: 0.9744


[0.08678094297647476, 0.974399983882904]

In [28]:
y_predited = model.predict(scaled_X_test)
y_predited_labels = [np.argmax(i) for i in y_predited]

313/313 [==============================] - 1s 2ms/step


Confusion Matrix

In [29]:
cm = tf.math.confusion_matrix(labels=y_test, predictions=y_predited_labels)
cm

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 968,    0,    0,    1,    1,    0,    5,    1,    4,    0],
       [   0, 1123,    2,    4,    0,    0,    2,    1,    3,    0],
       [   3,    7,  988,    5,    1,    0,    3,   18,    7,    0],
       [   0,    0,    3,  997,    0,    1,    0,    6,    3,    0],
       [   0,    0,    4,    1,  961,    1,    6,    2,    2,    5],
       [   3,    0,    0,   19,    1,  857,    4,    3,    4,    1],
       [   2,    2,    1,    1,    3,    3,  942,    2,    2,    0],
       [   1,    4,    8,    3,    1,    0,    0, 1004,    2,    5],
       [   1,    0,    3,    9,    8,    4,    1,    6,  940,    2],
       [   1,    2,    0,   10,   14,    4,    2,    6,    6,  964]])>

In [30]:
fig = ff.create_annotated_heatmap(z=cm.numpy(), x=list(range(10)), y=list(range(10)), colorscale='Viridis', showscale=True)
fig.update_layout(title='Confusion Matrix', xaxis_title='Predicted', yaxis_title='Actual')
fig.show()